### ISSUE TITLE
Animations should not cancel parent animations

### ISSUE THREAD

**Issue by jonrimmer** [angular/angular.js#11975]
1.4 has broken some important animations in my application. Apparently this is because ng-enter animations have been modified to cancel running ng-class animations on their parents, for some insane reason?

I have a container element with a router ui-view nested inside it. The container has an ng-class that sets 'active' on the container when a particular route becomes active, which is then used to slide the container into view. The ui-view element itself has an ng-enter animation that transitions its opacity.

In 1.3 this all worked perfectly. In 1.4 it is broken, because the framework apparently thinks that, because I'm animating the opacity of one element, I mustn't want the position animation—that I have *explicitly specified*—on its parent to run. In what universe is this desirable behaviour?

**Comment by Narretz** [comment]
Yesh, this happened in https://github.com/angular/angular.js/commit/c8700f04fb6fb5dc21ac24de8665c0476d6db5ef

It does seem very limiting. @matsko do you have an idea how this can be remdied?

**Comment by matsko** [comment]
Yes I'm working on a full fix. It should be ready towards the end of the week and in time for 1.4.1

**Comment by matsko** [comment]
This PR should fix it: https://github.com/angular/angular.js/pull/12248

**Comment by matsko** [comment]
This is now fixed in master.

**Comment by jonrimmer** [comment]
:+1:

**Comment by jonrimmer** [comment]
Perhaps I am missing something, but this still does not seem to be working in 1.4.3.

Take a look at the following Plunkr, which shows a simplified version of the kind of thing I am doing. I'm using ng-class to toggle an "active" class on a sidebar depending on the current ui-router state.

http://plnkr.co/edit/xDMuBc?p=preview

In 1.3.17 it works. If you change the version to 1.4.3, it doesn't. Is there some other change between the versions that is breaking this that I'm unaware of?

**Comment by Narretz** [comment]
@jonrimmer the fix is not in a release yet. It's in master so you should test with the current snapshot. It will be part of 1.4.4

**Comment by jonrimmer** [comment]
Ah, OK, thanks. I was going by the [changelog](https://github.com/angular/angular.js/blob/master/CHANGELOG.md), which is showing this as fixed in 1.4.3. Thanks!

**Comment by poshest** [comment]
Is this the same issue?  I have a [Plunkr](http://plnkr.co/edit/IyHbJa4mMydBlcwErMPf?p=preview) where the animate on the outer div with `ng-show` doesn't work in 1.4.x because of the presence of the child `ng-if`.  It works by either

 - removing the `ng-if`, or
 - downgrading to <1.3.x Angular file versions

Haven't tried latest 1.4.4 candidate yet - not sure how to since the latest code is not yet on the CDN or [Angular](https://code.angularjs.org/). Is 1.4.4 near release?

**Comment by poshest** [comment]
In answer to my question, 1.4.4 just released does fix my problem too.  Must have been the same or similar problem.
