### ISSUE TITLE
attrs has attributes for all scope properties in 1.4.1 not in 1.2.26

### ISSUE THREAD

**Issue by frfancha** [angular/angular.js#12209]
We have a breaking change migrating from 1.2.26 to 1.4.1 that I don't find in the doc, but perhaps I'm not looking correclty.
In 1.2.26 when you have a directive with:
scope: {
firstProp: '@',
secondProp: '@'
}
but only use firstProp in your html, the property secondProp of the object attrs received by the link function just doesn't exist.
In 1.4.1, the property secondProp exists (and is undefined).
As we had code using attrs.hasOwnProperty('secondProp') this was a breaking change for us.
Is this a wanted change? Then could you help me to find where it was described in the docs?
Thanks.

**Comment by gkalpak** [comment]
This was an unintended regression and has been fixed on master (8a1eb16).
The fix will be included in 1.4.2.

**Comment by frfancha** [comment]
@gkalpak we still have the bug in 1.4.3, is this correct? Is there a new version planned to include the correction?
We have discovered that this problem can cause much more annoyance than we first thought:
in some scenario where directives can be ued by optional param p1 or p2, and using params p2 computes p1, not using parameter p1 will erases computation from p2 by undefined.

**Comment by gkalpak** [comment]
@frfancha, iirc it was indeed fixed in 1.4.2, but the fix was reverted in 1.4.3 (because it broke some stuff in other libraries (read angular-material)) and it has been fixed (properly) in 533d9b7, so it will be available 1.4.4 (which will be out next week I guess).

**Comment by frfancha** [comment]
@gkalpak Ok thanks for the explanation. We will test again in 1.4.4 then.
