### ISSUE TITLE
angular docs not working

### ISSUE THREAD

**Issue by myrubapa** [angular/angular.js#12963]
![screenshot from 2015-09-27 22 24 33](https://cloud.githubusercontent.com/assets/1535825/10124142/db220ac2-6566-11e5-9610-eb544c5f7c55.png)

**Comment by pjduerden** [comment]
Also seeing this problem.

**Comment by yjukaku** [comment]
:+1:

**Comment by lgalfaso** [comment]
@petebacondarwin can you please check this out? It looks like https://docs.angularjs.org/js/versions-data.js is not there

**Comment by csvan** [comment]
Confirming, the entire doc system fails to bootstrap.

**Comment by yjukaku** [comment]
It's actually been like this for about a day now, IIRC.

**Comment by lgalfaso** [comment]
it should be working now

**Comment by Narretz** [comment]
Did you change something @lgalfaso? Because I still get the broken page. It works after CTRL + F5, though, so something is fishy.

**Comment by lgalfaso** [comment]
@Narretz it looks like there is some flakiness with the ci, and when a commit goes in and the documentation generation fails, then the docs are down.
The only thing I did was to merge a PR and check the docs ~15 minutes later. Now another PR went it and the ci failed and the docs are down

**Comment by petebacondarwin** [comment]
This is still not resolved. @btford and I are looking into it.
I believe the problem is that the servers failed to synchronise with the code.angularjs.org repository when it got updated and have now got into a dirty state which is preventing them from updating correctly.

**Comment by adiakritos** [comment]
Still having this issue when I search certain pages. This is the animation docs. 

https://www.dropbox.com/s/ht7mgajbsmfr106/Screenshot%202015-09-27%2014.25.30.png?dl=0

**Comment by Narretz** [comment]
The docs are back up!
