### ISSUE TITLE
ng-options duplicates all <option> entries if manual <option> included with ng-if directive on it.

### ISSUE THREAD

**Issue by pavlovich** [angular/angular.js#13065]
If I create a <select> and use ng-options to populate the available options, and if I want to include a default option using a child <option> element but I want that inclusion to be conditional specified with a ng-if directive, then ng-options will duplicate all of the options. If I use ng-show instead of ng-if, all works as I would expect.

See the following plunker: http://plnkr.co/edit/eXkvYQvsyPKEjPKEndhZ?p=preview

**Comment by pkozlowski-opensource** [comment]
It looks like it is fixed in master: http://plnkr.co/edit/eXkvYQvsyPKEjPKEndhZ?p=preview

**Comment by pavlovich** [comment]
I clicked on the link you provided (the plunker) but found that it was
still broken in that plunker. Can you point me to an updated plunker that
shows this working on master?

**Comment by pkozlowski-opensource** [comment]
@pavlovich sorry, copied the wrong link. Here you go: http://plnkr.co/edit/GmCbsH0xrMPxviMFD2Qv?p=preview

You can always reference build from master using https://code.angularjs.org/snapshot/

**Comment by pavlovich** [comment]
Actually, the plunker at the link you provided does not work! It does not
add the 'extra' / 'default' choice to the list at all now. If I remove the
ng-if or change it to an ng-show, it works. As it is in the plunker, it is
non-functional (the extra item does not show up regardless of the value of
the ng-if).

Best regards,

Peter

**Comment by gkalpak** [comment]
Closing as duplicate of #12190.
Track #13029 for a solution.
