### ISSUE TITLE
ngAnimate breaks ngRepeat

### ISSUE THREAD

**Issue by ChristianLorza** [angular/angular.js#13764]
I am very new to coding in general so other threads have not been really able to help me.

When I attempt to use ngAnimate it stops my ngRepeat from working and also creates duplicates.
Example: https://gyazo.com/13df8b9e13e3dda1a2a22b469f293a7e

Here are images of my code:
html/css: https://gyazo.com/ae76cf3abd929cb7c52c77c6bf1dcab0
javascript: https://gyazo.com/46604433c620b859c00c374aeb3ba6d4

Please help :(

this code works perfectly fine if i remove ngAnimate as a dependency

Thank you.

**Comment by Narretz** [comment]
Hi,
two things: questions like these are better asked on one of the support channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
And while the gif is great, the code in the image is not very good. It's better to put your example in something like plnkr.co, so that we can play around with it.

**Comment by ChristianLorza** [comment]
Thanks for the feedback.
I've not used plnkr.co before however I'd played around and here's my code:

http://plnkr.co/edit/HZq6gMCMrRr6wfUs1oAJ?p=catalogue

**Comment by Narretz** [comment]
The plnkr doesn't work. Did you forget to save it? Here's fixed version, only the data.json is missing: http://plnkr.co/edit/0enbtZG0Si6lbzeFET0t?p=preview

**Comment by ChristianLorza** [comment]
http://plnkr.co/edit/bqotrLBexDQXD3Tdrm7G?p=preview
Here's the json data.

also $http.get() is just not working.
I get something related to CORS

but that's an issue for another section i suppose.

**Comment by Narretz** [comment]
Here we go ... http://plnkr.co/edit/pg1ZPC1FTft06kXLOs1g?p=preview

But I can't reproduce the error. What are the steps to reproduce?

**Comment by ChristianLorza** [comment]
hmm, i copied and pasted the code exactly into sublime. 
and the error persisted.

**Comment by ChristianLorza** [comment]
https://gyazo.com/9e7841e0008900ba2db339ca836d82ac <-- $http.get() error

**Comment by Narretz** [comment]
Did you see my last plunker link? I fixed the http error for you.
Now I want to know what I have to do to produce the repeat / animation bug, because I cannot reproduce it.
Also, once again, it's better to copy / paste text inside your comments instead of creating images.

**Comment by ChristianLorza** [comment]
I copied the code exactly into sublime.
The $http.get() error is still there for me.

**Comment by Narretz** [comment]
I don't know why that is. But the plnkr works now, so can you tell me what I have to do to make the duplication bug appear?

**Comment by ChristianLorza** [comment]
i dont know. 
The code that I initially posted produces both issues. 
the code works fine on plunker but not for me locally.

**Comment by ChristianLorza** [comment]
its rather strange. 
If i remove the ngAnimate dependency and run the file in firefox it works fine.

**Comment by Narretz** [comment]
Your gifs are too fast ... I cannot see when the duplicates happen.

**Comment by Narretz** [comment]
Ok, if you can't reproduce the error, I'm gonna close this issue. Feel free to reopen it when you have a reproduction.

One thing I've seen is that you seem to be using a custom ngAnimate file in your original example. The plnkr uses angular-animate at version 1.4.5. Maybe that was the problem?
