### ISSUE TITLE
Changes in animation's behavior starting from 1.4.7

### ISSUE THREAD

**Issue by havenchyk** [angular/angular.js#13838]
Hi,

I've recently updated from 1.4.3 and found changes in the animation's behavior. 

My code is something like this, nothing specific:

```
<div ng-if="var1">
  <div ng-show="var2"></div>
  <div ng-if="var3"></div>
</div>
```

But what I see after update starting from 1.4.7 is random flickering on the nested `ng-if`.

I'll try to provide an example, but could anyone review this issue and say, is it a bug or just undocumented changes in the behavior?

I can debug only changes in `data-ng-animate` attribute: they are 1 and 2. Also I don't see any animation specific classes on the divs, like `ng-enter`, `ng-leave` etc

**Comment by Narretz** [comment]
Can you please post a plnkr.co etc. that shows the problem? We've fixed a lot of bugs in ngAnimate, but there's also a known issue with nested animations.

**Comment by Narretz** [comment]
You should also see if the problem persists in 1.4.9.

**Comment by havenchyk** [comment]
The problem persists in all the versions after 1.4.7, oncluding 1.5.0-rc1

**Comment by Narretz** [comment]
@havenchyk Ok. Please try to get a working demo running.

**Comment by havenchyk** [comment]
@Narretz unfortunately I haven't been able to pull the example from my application, but it looks like that the problem is similar like described here https://docs.angularjs.org/guide/animations#preventing-flicker-before-an-animation-starts

So, I've added styles for `ng-enter-prepare` and `ng-leave-prepare` and now things are better, but I get some flickering even after this workaround. 

Maybe guys you can advice, how to debug angular animations and for what things I need to take a look, I'd like to help, but don't know how.

**Comment by havenchyk** [comment]
Ok, [here is](http://jsbin.com/fumugofuvo/3/edit?html,css,js,console,output) something similar that I have. If you click on the button, you will see "jumps" down of the button.

**Comment by Narretz** [comment]
This is a result of https://github.com/angular/angular.js/commit/ea8016c4c8f55bc021549f342618ed869998e335, which went into 1.4.5. As of now, this is expected behavior, unfortunately.
Applying display: none only to the enter animation removes the flicker: http://jsbin.com/diwixeziba/1/edit?html,css,js,output
This makes sense. The enter element is added to the DOM, and because it's a child element, the regular display: none is only applied after an animationFrame. So there's a very short time frame where the element is visible, even though it shouldn't be. With leave, we don't have this problem, because the element is already there. Probably should make this more clear in the guide.

**Comment by havenchyk** [comment]
@Narretz heh, it solves my problem. It would be great if you could add details to the guide, it was unclear for me before your comment. 

Thanks!

**Comment by havenchyk** [comment]
BTW, I still have flickering even after `display: none`. Animation disabling with `$animate.enabled(element, false)` solves the problem, but it's a workaround as well.

**Comment by Narretz** [comment]
@havenchyk Which browser is that?

**Comment by havenchyk** [comment]
Latest Google Chrome and Chrome Canary

**Comment by Narretz** [comment]
Hm, I can't reproduce this. I've used the jsbin I linked to.

**Comment by Narretz** [comment]
@havenchyk What OS are you using?

**Comment by havenchyk** [comment]
@Narretz I can't reproduce the issue with an example on jsbin, but have it in my complex application. I use win7 and the problem can be reproduced in latest Google Chrome, FF and IE11. Current workaround is to disable animation with `$animate.enabled(element, false);`

**Comment by Narretz** [comment]
@havenchyk At the moment, this is an expected side-effect of a change in 1.4.5 that was necessary to fix other bugs. We've introduced a new class that can be used to prevent the flicker. Mabye it works for you: https://code.angularjs.org/snapshot/docs/guide/animations#preventing-flicker-before-an-animation-starts

**Comment by havenchyk** [comment]
@Narretz if you check our previous comments on current issue, you will see that I already tried it and it doesn't work for me. I'll attach video to show, what's going on, because I can't reproduce the issue from the scratch.

**Comment by Narretz** [comment]
@havenchyk Sorry, I confused this issue with the one that you linked.

**Comment by teterovic** [comment]
@havenchyk check if you updated your angular-animate to the latest version

**Comment by havenchyk** [comment]
@teterovic of course I updated it as well.

**Comment by Narretz** [comment]
I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction (ideally a runnable demo in a https://plnkr.co or similar. You can use this [Plunker Template](http://plnkr.co/edit/tpl:yBpEi4)).
