### ISSUE TITLE
Angular lacks support for recursive directives

### ISSUE THREAD

**Issue by robstolarz** [angular/angular.js#8536]
This is a pretty major issue in terms of being able to do things "the Angular way."  
My model is a tree. Trees require recursion. I'm making an app that depends on a directive that allows movement of nodes inside a tree. In order to be able to move nodes inside this tree, I need to place "drop zones" which will detect elements that are dropped onto them. ![1]   
Unfortunately, with the "Angular way" of implementing this ([2] is a JSFiddle that uses similar concepts; recursive directive with transcluded template for each node of the tree) the transcluded template is rendered totally unaware of where it is located relative to where its data comes from, because the transcluded template has to be removed from its parent element before compilation.   
If it's removed, it loses its scope; if it's not removed, [3] happens. (Open a console, you'll see the infinite recursion. It's the same as [2] but with the compile function commented out.) Angular tries to compile the directive while it's already compiling the directive, which fails hopelessly.

Now, there are workarounds, which is why it is possible that angular-ui-tree [4] exists. However, the only way to use it is through a recursive template ([5] is a good starting point) which misses out on all the cool directive support and parametrization and is generally not the intended use of templates. The implementation here becomes hairier than it needs to be because of the lack of support for recursive directives.

[1]: http://i.imgur.com/nYZQ7hO.png
[2]: http://jsfiddle.net/DsvX6/7/
[3]: http://plnkr.co/edit/nG5whvN2jPWDxLTBqTDo?p=preview
[4]: https://github.com/JimLiu/angular-ui-tree
[5]: http://stackoverflow.com/questions/14430655/recursion-in-angular-directives

**Comment by nhhockeyplayer** [comment]
Folks, is there a consensus on this ? Whats appropriate to commit to. Whats available for commercial ?

**Comment by callmeStriking** [comment]
Angular 1 will not have native support for recursion. Use any of the previously mentioned solutions to do it, or use a framework more suitable for your project.

**Comment by nhhockeyplayer** [comment]
Well I have implemented several trees in the past recursive ones. Doesn't what this gentleman is doing jar anyone's mins as to the possibilities here ?

https://www.youtube.com/watch?v=vJqJ-0U74IY

I am thinking not outside of the box (angular) but thinking deeper inside the box (javascript).
Whats wrong with taking what angular offers and souping it up with some snazzy javascript in between the seams. ?

??

I havent seen anything yet that is causing me to jump up and start doing back flips.

I did a struts-tiles tree years back that I recall qualifies similarly structurally to whats available this moment in angular and javascript that would provide a sound commercial grade load and erect tree-widget based on some json structure and could be implemented to do-all...click, click-open, click-drag, click-close... on nodes and branches. And add/delete too.

I am still looking to do it myself but wondering if anyone has done this already.

**Comment by callmeStriking** [comment]
Few people have done anything of merit that you can use commercially. Good luck with your custom solution, hope you open-source it.

**Comment by schmod** [comment]
Is there any solution on the roadmap for this?  It's pretty glaring that this is still an issue.

**Comment by lgalfaso** [comment]
To some extend, this will be solved once #12078 lands, and there is a reasonable chance that it will make it for 1.5. Given that this is a breaking change, it is not possible for it to land before.

**Comment by schmod** [comment]
That's fantastic, and I doubt that there's a solution to this problem that wouldn't involve a breaking change.  This issue has been a thorn in my side for way too long -- angular's supposed to be good at building things like tree-views.

**Comment by jeme** [comment]
Just to add an update on this from the https://github.com/dotJEM/angular-tree perspective.

Which have been moved to use Transclude instead of compile, which speeds it up a high degree, so the previous statement of being lazy evaluated.

**Comment by schmod** [comment]
So, does Angular 1.5 now provide a reasonable path for creating trees without using `$compile`?

My intuition seems to suggest that this is possible, but I'm not quite sure what the recommended path for doing it would be.

**Comment by lgalfaso** [comment]
@schmod it depends on the specific case, but most simple solutions work. Eg if the recursive reference in the directive template is inside an `ngIf` or `ngSwitch` that controls if the recursion should happen, then that is enough.

**Comment by jeme** [comment]
@schmod that depends on preference, but I would think the following example is reasonable and very simple? https://plnkr.co/edit/5Qv1pN4ISbRxvGnsUVgN?p=preview

```
app.controller('appController', function() {
  
  this.data = { 
    name: 'TEST',
    nodes: [
      { name: 'Child1', 
        nodes: [
          { name: 'GrandChild',
            nodes: [
              { name: 'GrandGrandChild' }
            ]
            
          }
        ]
      },
      { name: 'Child1', 
        nodes: [
          { name: 'GrandChild' }
        ]
      },
      { name: 'Child1', 
        nodes: [
          { name: 'GrandChild' }
        ]
      }
    ]
  };
});

app.directive('recurseMe', function() {
  return {
    scope: { 
      tree: '='
    },
    template: '<ul>'
            + '<li ng-repeat="node in tree.nodes">'
            + 'NAME: {{ node.name }}'
            + '<recurse-me tree="node" />'
            + '</li>'
            + '<ul>'
  }
});
```

**Comment by petebacondarwin** [comment]
@jeme To get this sort of thing to work we must squeeze some asynchronicity into the template. Some people have used `ngInclude` to inject the child node template; others, as mentioned by @lgalfaso, use `ngIf`, etc; still others have actually added an explicit `$timeout(..., 0)` to get the same result.

The key is that we need the child nodes to be rendered in a subsequent digest and not the current one.
The way it is working in your example the `recurseMe` directive is being rendered recursively synchronously in the same digest - this causes a new digest loop (or possibly multiple digest loops) for each recursion. Eventually that will hit the $scope TTL limit.

**Comment by lgalfaso** [comment]
@petebacondarwin the example that @jeme posted works well as the recursion is inside an `ngRepeat`. Am I missing something else from your answer?

**Comment by petebacondarwin** [comment]
Sorry I meant to reply to @school not @jeme. Yes, `ngRepeat` also provides this asynchronicity
